### ISSUE TITLE
使用它写tars client调用tars服务不成功

### ISSUE THREAD

**Issue by suhanyujie** [jackylee92/doTars#2]
* 查看日志，提示如下：

```html
[2018-12-24 20:39:34] tars_logger.INFO: stat/property/keepalive/config/logger service init start...  [] []

Fatal error: Uncaught Error: Class 'Tars\monitor\StatFServer' not found in /usr/local/app/tars/tarsnode/data/Client.SuhanyuTest/bin/src/vendor/phptars/tars-server/src/core/Server.php:101
Stack trace:
#0 /usr/local/app/tars/tarsnode/data/Client.SuhanyuTest/bin/src/vendor/phptars/tars-server/src/cmd/Start.php(68): Tars\core\Server->start()
#1 /usr/local/app/tars/tarsnode/data/Client.SuhanyuTest/bin/src/vendor/phptars/tars-server/src/cmd/Command.php(29): Tars\cmd\Start->execute()
#2 /usr/local/app/tars/tarsnode/data/Client.SuhanyuTest/bin/src/index.php(11): Tars\cmd\Command->run()
#3 {main}
  thrown in /usr/local/app/tars/tarsnode/data/Client.SuhanyuTest/bin/src/vendor/phptars/tars-server/src/core/Server.php on line 101
```

**Comment by jackylee92** [comment]
已修复，请使用 v2.0.6版本
